### ISSUE TITLE
Error - Deploy into Firebase Hosting with GitHub Actions

### ISSUE THREAD

**Issue by RecepCil** [RecepCil/mtdb#13]
Deploy process returns an error because of that build folder is gitignored. 

Error: [Specified public directory 'build' does not exist, can't deploy hosting to site](https://github.com/RecepCil/mtdb/runs/1846352205?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/18148117/107128595-00276480-68d0-11eb-97b1-dc6916b693f8.png)

#
**Related files:**
[firebase.json](https://github.com/RecepCil/mtdb/blob/master/firebase.json)
[firebase-hosting.yml](https://github.com/RecepCil/mtdb/blob/master/.github/workflows/firebase-hosting.yml)

**Comment by RecepCil** [comment]
Problem was caused of lack of the the build folder path. 5. line was missing.

```
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          **path: build**
```
